### ISSUE TITLE
npm  run dev:rn 报错: [BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".

### ISSUE THREAD

**Issue by gclsoft** [NervJS/taro-sample-weapp#1]
```
缺少npm包babel-plugin-transform-jsx-to-stylesheet，开始安装...
(node:26065) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at write (console.js:165:9)
    at Console.log (console.js:197:3)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:41:15)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:47:14)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:47:14)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:47:14)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:47:14)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:47:14)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:47:14)
    at resolveNpmSync (/usr/local/lib/node_modules/@tarojs/cli/src/util/npm.js:47:14)
(node:26065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26065) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
我把babel-plugin-transform-jsx-to-stylesheet加到安装后, 就报这个错误:
```
开始编译项目 taro-sample-weapp
编译  JS        /Users/apple/Downloads/taro-sample-weapp-master/src/app.js
编译  SCSS      /Users/apple/Downloads/taro-sample-weapp-master/src/app.scss
编译  JS        /Users/apple/Downloads/taro-sample-weapp-master/src/utils/util.js
编译  JS        /Users/apple/Downloads/taro-sample-weapp-master/src/components/ec-canvas/ec-canvas.js
编译  JS        /Users/apple/Downloads/taro-sample-weapp-master/src/components/ec-canvas/echarts.js
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".
(node:26311) UnhandledPromiseRejectionWarning: TypeError: Property consequent of ConditionalExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at CallExpression (/usr/local/lib/node_modules/@tarojs/cli/src/rn.js:388:25)
    at NodePath._call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/context.js:150:16)
(node:26311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26311) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gclsoft** [comment]
环境是在mac下

**Comment by Pines-Cheng** [comment]
这是 Taro 与小程序原生融合的示例项目，包括：

- wxParse 示例
- echarts-for-weixin 示例
- 混写原生页面示例

**Comment by gclsoft** [comment]
@Pines-Cheng 不是支持编译到nt到ios上吗?

**Comment by gclsoft** [comment]
@Pines-Cheng 不是支持编译到nt到ios上吗?
