### ISSUE TITLE
运行报错Expect FLOW_CREATE_NODE but get another

### ISSUE THREAD

**Issue by lavi2510** [NervJS/taro-sample-weapp#2]
webviewScriptError
Expect FLOW_CREATE_NODE but get another
Error: Expect FLOW_CREATE_NODE but get another
    at e.value (http://127.0.0.1:58513/__pageframe__/__dev__/WAWebview.js:23:18730)
    at http://127.0.0.1:58513/__pageframe__/__dev__/WAWebview.js:23:19067
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:58513/__pageframe__/__dev__/WAWebview.js:23:19039)
    at http://127.0.0.1:58513/__pageframe__/__dev__/WAWebview.js:23:19067
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:58513/__pageframe__/__dev__/WAWebview.js:23:19039)
    at http://127.0.0.1:58513/__pageframe__/__dev__/WAWebview.js:23:19067
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:58513/__pageframe__/__dev__/WAWebview.js:23:19039)

**Comment by luckyadam** [comment]
请问在哪个页面的错
以及你的 Taro 版本多少
