### ISSUE TITLE
taro v3.0.0-beta.3 运行失败

### ISSUE THREAD

**Issue by wangweifeng66** [NervJS/taro-sample-weapp#33]
taro build --type weapp --watch编译成功后，微信小程序编辑器控制台报错，taro doctor有很多错误，小程序控制到报错如下：
thirdScriptError
_taroWeapp2.default.RefsArray is not a constructor
TypeError: _taroWeapp2.default.RefsArray is not a constructor
    at Index._constructor (http://127.0.0.1:21089/appservice/pages/index/index.js:81:21)
    at Object.createComponent (http://127.0.0.1:21089/appservice/taro.js:1955:55)
    at Object.3 (http://127.0.0.1:21089/appservice/pages/index/index.js:158:42)
    at __webpack_require__ (http://127.0.0.1:21089/appservice/runtime.js:80:30)
    at Module.10 (http://127.0.0.1:21089/appservice/pages/index/index.js:8:172)
    at __webpack_require__ (http://127.0.0.1:21089/appservice/runtime.js:80:30)
    at Module.32 (http://127.0.0.1:21089/appservice/pages/index/index.js:168:96)
    at __webpack_require__ (http://127.0.0.1:21089/appservice/runtime.js:80:30)
    at checkDeferredModules (http://127.0.0.1:21089/appservice/runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:21089/appservice/runtime.js:33:19)

Page "pages/index/index" has not been registered yet.

**Comment by yuche** [comment]
你应该在 next 和 vue 分支运行，taro doctor 还没适配 next
